import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Providers } from "../providers";
import { headers } from "next/headers";

import "../globals.css";
import Loader from "@/components/shared/Loader";
import AuthWrapper from "@/components/shared/AuthWrapper";
import { Locale } from "@/utils/types/shared/common";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  const cookie = headers().get("cookie");

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <NextIntlClientProvider messages={messages}>
          <Providers locale={locale as Locale} cookie={cookie}>
            <AuthWrapper>
              <Loader />
              {children}
            </AuthWrapper>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
